Starting with importing the pandas library

In [8]:
import pandas as pd

Lets load the dataset from my GitHub account to ensure this can be run without saving the file locally and display the data

In [9]:
df = pd.read_csv('https://github.com/KcirtapdiaZ/IS_362_Data_Acquisition_and_Mgmt/raw/main/IS362_Week7_Assignment.csv')
df

,Unnamed: 0,Scream 7,Frankenstein,Marty Supreme,The Housemaid,Dracula,Eternity
0,Ellen,3.0,NaN,NaN,3,5.0,4.0
1,Jonathan,NaN,4.0,2.0,3,3.0,NaN
2,Shelby,3.0,4.0,NaN,3,NaN,3.0
3,Kate,2.0,4.0,2.0,4,3.0,NaN
4,Will,NaN,5.0,4.0,2,3.0,2.0

The first column are the names so we will use this as the index. This will make it easier to the make calculations. Also to make it look cleaner we'll rename the index

In [10]:
df = df.set_index('Unnamed: 0')
df.index.name = 'User'
df

,Scream 7,Frankenstein,Marty Supreme,The Housemaid,Dracula,Eternity
User,,,,,,
Ellen,3.0,NaN,NaN,3,5.0,4.0
Jonathan,NaN,4.0,2.0,3,3.0,NaN
Shelby,3.0,4.0,NaN,3,NaN,3.0
Kate,2.0,4.0,2.0,4,3.0,NaN
Will,NaN,5.0,4.0,2,3.0,2.0

Since the indexing is done, we will start with calculating the average rating for each movie. To calculate this we'll use .mean so calculate the average of each movie.

In [11]:
movie_avg = df.mean()
print ("Average rating for each movie:")
print (movie_avg)

Average rating for each movie:
Scream 7         2.666667
Frankenstein     4.250000
Marty Supreme    2.666667
The Housemaid    3.000000
Dracula          3.500000
Eternity         3.000000
dtype: float64

Now we'll do the same for the average rating for each user

In [12]:
user_avg = df.mean(axis=1)
print ("Average rating for each user:")
print (user_avg)

Average rating for each user:
User
Ellen       3.75
Jonathan    3.00
Shelby      3.25
Kate        3.00
Will        3.20
dtype: float64

We now need to create a new pandas dataframe with normalized ratings for each user. To do this well remove personal rating bias by subtracting each users average rating from thier ratings. To do this we'll use .sub and axis to make sure the subtraction is occurring by row and target the user average rating

In [14]:
normalized = df.sub(df.mean(axis=1), axis=0)
print ("Normalized ratings:")
print (normalized)

Normalized ratings:
          Scream 7  Frankenstein  Marty Supreme  The Housemaid  Dracula  \
User
Ellen        -0.75           NaN            NaN          -0.75     1.25
Jonathan       NaN          1.00           -1.0           0.00     0.00
Shelby       -0.25          0.75            NaN          -0.25      NaN
Kate         -1.00          1.00           -1.0           1.00     0.00
Will           NaN          1.80            0.8          -1.20    -0.20

          Eternity
User
Ellen         0.25
Jonathan       NaN
Shelby       -0.25
Kate           NaN
Will         -1.20

Now, we'll show the average ratings for each user and movie with the normalized ratings, again using .mean

In [17]:
print ("Average normalized rating for each movie:")
print (normalized.mean())

print ("Average normalized rating for each user:")
print (normalized.mean(axis=1))

Average normalized rating for each movie:
Scream 7        -0.666667
Frankenstein     1.137500
Marty Supreme   -0.400000
The Housemaid   -0.240000
Dracula          0.262500
Eternity        -0.400000
dtype: float64
Average normalized rating for each user:
User
Ellen       0.000000e+00
Jonathan    0.000000e+00
Shelby      0.000000e+00
Kate        0.000000e+00
Will       -1.776357e-16
dtype: float64

Using normalized ratings make it easier to compare users because it adjust for differences in how people rate movies. Some people may rate movies high constantly, while some may rate movies low consistantly. Normalization would help by centering each users ratings. A drawback would be that normalized values do not refelct the original rating scale, in this case 1-5.