Using the third dataset List of NBA players Stats

The objective will be to turn this wide format into long format to see player stats more easily 

Dataset Source: https://www.nba.com/stats/players/traditional?sort=PTS&dir=-1%29

First we will import pandas

In [27]:
import pandas as pd

Next we will load the csv. I uploaded the csv to my GitHub so I can pull from there instead of the local PC. I will define the variable as df and use the read_csv() function to load the csv into pandas. I will us df line to show the data.

In [30]:
df = pd.read_csv('https://github.com/KcirtapdiaZ/IS_362_Data_Acquisition_and_Mgmt/raw/main/IS362_Project2_Dataset3.csv')
df

,Unnamed: 0,Player,Team,Age,GP,W,L,Min,PTS,FGM,...,REB,AST,TOV,STL,BLK,PF,FP,DD2,TD3,+/-
0,1,Tyrese Maxey,PHI,25,$58,32,26,2232.9,1690,588,...,239,394,141,118,46,129,2919,7,0,124
1,2,Shai Gilgeous-Alexander,OKC,27,$51,40,11,1697.0,1621,557,...,225,328,107,70,40,103,2606,5,0,579
2,3,Donovan Mitchell,CLE,29,$55,35,20,1840.1,1570,546,...,247,320,170,86,15,132,2479,4,0,357
3,4,Jaylen Brown,BOS,29,$54,35,19,1850.3,1568,579,...,385,269,194,54,24,148,2474,12,3,188
4,5,Luka Don?i?,LAL,27,$48,30,18,1698.1,1559,496,...,368,414,191,68,24,116,2707,27,6,68
5,6,Anthony Edwards,MIN,24,$51,32,19,1817.4,1502,522,...,265,190,144,69,42,92,2294,2,0,165
6,7,Kevin Durant,HOU,37,$57,35,22,2085.0,1497,525,...,310,258,181,46,51,113,2366,6,0,305
7,8,Jalen Brunson,NYK,29,$56,38,18,1936.7,1494,530,...,192,342,127,38,7,135,2245,6,0,267
8,9,Jamal Murray,DEN,29,$57,34,23,2005.4,1463,509,...,250,415,138,56,21,91,2479,15,0,264
9,10,Cade Cunningham,DET,24,$53,40,13,1855.6,1350,478,...,308,519,199,80,50,167,2689,33,3,433
10,11,Nikola Joki?,DEN,31,$46,28,18,1590.0,1318,464,...,580,476,169,62,36,126,2853,40,22,406
11,12,Julius Randle,MIN,31,$61,38,23,2036.5,1313,458,...,418,327,158,66,16,174,2393,14,3,224
12,13,Kawhi Leonard,LAC,34,$46,25,21,1498.9,1280,447,...,291,172,101,92,23,57,2131,5,0,164
13,14,James Harden,CLE,36,$52,28,24,1820.8,1272,371,...,253,422,190,63,21,105,2271,16,2,61
14,15,Brandon Ingram,TOR,28,$58,34,24,1973.2,1268,473,...,336,221,144,44,45,114,2126,2,0,54
15,16,Jalen Johnson,ATL,24,$55,29,26,1931.6,1251,463,...,581,437,186,72,27,120,2715,38,11,36
16,17,Pascal Siakam,IND,31,$52,14,38,1752.3,1241,467,...,351,204,116,57,23,127,2092,9,0,-157
17,18,Desmond Bane,ORL,27,$59,31,28,2016.5,1196,433,...,246,244,123,58,29,182,1995,1,0,67
18,19,Keyonte George,UTA,22,$50,15,35,1682.3,1194,376,...,191,319,162,56,14,115,1950,4,0,-330
19,20,Michael Porter Jr.,BKN,27,$48,13,35,1564.7,1174,415,...,336,150,114,50,11,105,1871,10,0,-171
20,21,Deni Avdija,POR,25,$48,23,25,1607.9,1173,359,...,338,318,184,38,28,126,2070,15,3,-52
21,22,Nickeil Alexander-Walker,ATL,27,$59,28,31,1952.5,1166,393,...,210,222,123,71,33,127,1940,2,0,-2
22,23,Trey Murphy III,NOP,25,$53,15,38,1884.1,1165,410,...,299,202,98,80,16,110,2017,4,0,-208
23,24,Kon Knueppel,CHA,20,$60,30,30,1912.9,1156,397,...,328,207,130,46,14,131,1910,5,0,188
24,25,DeMar DeRozan,SAC,36,$62,14,48,1967.1,1130,393,...,190,246,68,70,18,123,1923,0,0,-501
25,26,Karl-Anthony Towns,NYK,30,$57,37,20,1780.5,1127,376,...,670,159,146,51,33,200,2276,41,0,355
26,27,Lauri Markkanen,UTA,28,$42,17,25,1442.6,1123,384,...,289,89,63,42,21,77,1729,5,0,-55
27,28,Scottie Barnes,TOR,24,$58,34,24,1982.5,1105,432,...,474,321,158,79,93,166,2513,24,2,172
28,29,Norman Powell,MIA,32,$49,27,22,1470.2,1103,367,...,177,126,100,59,11,105,1614,1,0,121
29,30,Victor Wembanyama,SAS,22,$46,33,13,1341.2,1091,372,...,515,134,121,44,132,125,2317,29,1,392
30,31,Devin Booker,PHX,29,$44,27,17,1467.0,1088,358,...,172,270,144,39,12,118,1708,5,0,150
31,32,Alperen Sengun,HOU,23,$53,34,19,1793.3,1084,424,...,486,332,172,71,58,168,2380,26,3,172
32,33,CJ McCollum,ATL,34,$57,22,35,1701.5,1068,390,...,195,202,97,43,22,106,1703,0,0,-110
33,34,Paolo Banchero,ORL,23,$49,24,25,1711.2,1067,354,...,417,245,142,33,33,93,1991,19,2,-55
34,35,Stephen Curry,GSW,37,$39,23,16,1221.7,1061,348,...,138,189,111,44,16,74,1579,3,0,62
35,36,Dillon Brooks,PHX,30,$50,30,20,1530.3,1044,383,...,183,88,89,52,8,166,1487,0,0,-33
36,37,Payton Pritchard,BOS,28,$60,40,20,1954.1,1027,386,...,247,325,78,47,5,85,1889,4,0,286
37,38,Shaedon Sharpe,POR,22,$48,22,26,1439.1,1025,386,...,212,126,144,68,6,95,1546,0,0,-59
38,39,Derrick White,BOS,31,$59,39,20,2027.3,1011,349,...,262,341,108,70,88,90,2203,1,0,496
39,40,Amen Thompson,HOU,23,$58,36,22,2142.7,1009,389,...,446,304,150,87,36,128,2219,13,0,277
40,41,Miles Bridges,CHA,27,$56,28,28,1785.5,1000,358,...,340,193,84,34,28,102,1800,6,0,32
41,42,Cooper Flagg,DAL,19,$49,17,32,1669.5,999,381,...,321,202,108,58,39,105,1870,8,0,-155
42,43,Immanuel Quickley,TOR,26,$57,34,23,1855.4,995,347,...,241,342,90,68,5,118,1926,7,0,109
43,44,Bam Adebayo,MIA,28,$53,26,27,1662.9,986,351,...,523,150,93,53,35,87,2010,24,0,265
44,45,LaMelo Ball,CHA,24,$51,27,24,1406.9,984,346,...,244,375,145,56,12,129,1898,8,1,314
45,46,Ryan Rollins,MIL,23,$58,24,34,1862.2,976,375,...,267,312,149,86,24,157,1945,2,0,-103
46,47,Zion Williamson,NOP,25,$45,16,29,1327.9,967,361,...,263,156,95,48,27,101,1647,5,0,-98
47,48,Mikal Bridges,NYK,29,$61,39,22,2072.9,959,384,...,250,244,64,92,49,123,1984,1,0,258
48,49,De'Aaron Fox,SAS,28,$51,37,14,1610.8,958,358,...,191,315,122,63,13,114,1766,6,0,210
49,50,Saddiq Bey,NOP,26,$55,18,37,1690.7,951,324,...,319,142,50,50,3,64,1656,6,0,-174

Since we are going to be turing in this in a long format we do want to keep some columns the way they . We will identify those columns now

In [ ]:
keep_columns = ["Player", "Team"]

Now we'll define the stat columns

In [32]:
stats_to_show = ["PTS", "REB", "AST", "STL", "BLK"]

Lastly we are going to need to turn the original columns into rows. we can use the .melt to perform this

In [35]:
df_new = df.melt(id_vars=keep_columns, value_vars=stats_to_show, var_name="Stat", value_name="Value")
df_new

                      Player Team Stat  Value
0               Tyrese Maxey  PHI  PTS   1690
1    Shai Gilgeous-Alexander  OKC  PTS   1621
2           Donovan Mitchell  CLE  PTS   1570
3               Jaylen Brown  BOS  PTS   1568
4                Luka Don?i?  LAL  PTS   1559
..                       ...  ...  ...    ...
245             Ryan Rollins  MIL  BLK     24
246          Zion Williamson  NOP  BLK     27
247            Mikal Bridges  NYK  BLK     49
248             De'Aaron Fox  SAS  BLK     13
249               Saddiq Bey  NOP  BLK      3

[250 rows x 4 columns]

Lastly, I think it would be best to group by the player name so that the stats per player are together to easily analyze. I think the .sort_values would be a good function to use

In [40]:
df_new = df_new.sort_values(["Player"])
df_new

              Player Team Stat  Value
131   Alperen Sengun  HOU  AST    332
231   Alperen Sengun  HOU  BLK     58
31    Alperen Sengun  HOU  PTS   1084
81    Alperen Sengun  HOU  REB    486
181   Alperen Sengun  HOU  STL     71
..               ...  ...  ...    ...
96   Zion Williamson  NOP  REB    263
146  Zion Williamson  NOP  AST    156
246  Zion Williamson  NOP  BLK     27
46   Zion Williamson  NOP  PTS    967
196  Zion Williamson  NOP  STL     48

[250 rows x 4 columns]

With this we can easily identify all the main stats for a player, which improves the readability and organization for analysis